### ISSUE TITLE
请问已经爬到的数据是否有存档

### ISSUE THREAD

**Issue by YIDAMU** [simoncos/weibo-complaint-crawler#1]
您好，

请问read me 里说的 “crawled complaint report data sample (36,075, up to 2018-08-30) " 是否有存档？ 如果有备份，能否分享一下?

十分感谢！

**Comment by simoncos** [comment]
链接：https://pan.baidu.com/s/1raeGg5giL4ov8kJqxqpg5g 
提取码：1024

**Comment by YIDAMU** [comment]
> 链接：https://pan.baidu.com/s/1raeGg5giL4ov8kJqxqpg5g 提取码：1024

好人一生平安，请问如何继续采集数据？我试了weibo.py 发现无法运行， 能否简单地讲一下如何运行本项目？
感谢！

**Comment by simoncos** [comment]
网页结构是一直在变的，爬虫太老已经不能用了，你需要学习爬虫的原理，参考目前code修改，或者自己重新做一个。

**Comment by YIDAMU** [comment]
> 网页结构是一直在变的，爬虫太老已经不能用了，你需要学习爬虫的原理，参考目前code修改，或者自己重新做一个。

感谢回复！
