### ISSUE TITLE
关于举报数据

### ISSUE THREAD

**Issue by ChiliBai** [simoncos/weibo-complaint-crawler#2]
你好，我根据你的Code修改对数据进行了采集，但是发现能够采集到的历史数据很有限。因为网页上最多可以访问500页，总共约1W条左右数据，想请问你之前在采集的时候是怎么处理这个问题的呢？

**Comment by simoncos** [comment]
那个时候微博还没有这个页数限制，现在看起来前端已经卡死，不会返回500页以后的历史数据了，所以爬虫本身没有优化的办法。

**Comment by ChiliBai** [comment]
好的谢谢你的解答。
